@extends("admin.layout.main")
@section("title","title")
@section("description","description")
@section("keywords","keywords")
@section("author","author")
@section("copyright","copyright")
@section("locale","locale")
@section("og_type","og_type")
@section("og_title","og_title")
@section("og_url","og_url")
@section("og_site_name","og_site_name")
@section("css")
@endsection
@section("toolbar")
@endsection
@section("content")

@endsection
@section("js")
@endsection
